### ISSUE TITLE
Database maintenance

### ISSUE THREAD

**Issue by vgeorge** [okfn-brasil/violencia-nao-tem-partido#10]
Usar o Google Docs para controle de informações é difícil em um projeto com múltiplos colaboradores. Sugiro armazenar os dados neste repositório em formato YAML ou JSON, que são fáceis de ler em qualquer linguagem de programação e são melhores do que o CSV para rastrear modificações. [Neste repositório](https://github.com/mapaslivres/localidades/commit/f2a532d048a474ff27303d090f17533c63b59910#diff-5da4c86b688902d9f7825ced11f25473) sobre localidades do Brasil eu uso o YAML para armazenar metadados de localidades e é possível saber exatamente o que mudou no histórico porque cada linha refere-se a uma propriedade.

Posso ajudar nesta transição, se for o caso.

**Comment by cuducos** [comment]
This is merely a MVP and we're sticking to Google Sheets duo to several reasons, among them:

* Allow non-tech people to easily contribute
* No need to develop/deploy a customized form and admin
* Allow the curatorial layer to be distributes within a non-tech team

Using Google Sheets allow us to easiliy tackle these three issues. I do agree with you that in the future this might be an issue, but by now, in a MVP mindset this is enough. I'm closing this issue by now, but we might re-open it in the near futre.
