### ISSUE TITLE
Fix image CSS issues

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/violencia-nao-tem-partido#6]
There are two issues with the images in the new UI.

1. They should fill up (even if cropped) the area, no need to keep the proportion like this:

<img width="1129" alt="pasted_image_09_10_18_17_25" src="https://user-images.githubusercontent.com/4732915/46696421-76283d80-cbe8-11e8-874d-94d03346ebc8.png">

2. There's a gap that needs to be removed:

<img width="1109" alt="pasted_image_09_10_18_17_27" src="https://user-images.githubusercontent.com/4732915/46696497-a4a61880-cbe8-11e8-84bf-ed9b40e17839.png">

**Comment by humrochagf** [comment]
I used the object-fit property to make it behave as a cover image, then set both width and height to 100% to keep the aspect ratio

**Comment by cuducos** [comment]
Many thanks, @humrochagf!

Closed by #7
