### ISSUE TITLE
Cases of violence

### ISSUE THREAD

**Issue by giovanisleite** [okfn-brasil/violencia-nao-tem-partido#8]
Issue topic to report cases of violence for political reasons

**Comment by giovanisleite** [comment]
[Facebook post](https://www.facebook.com/dceufpr/posts/1908688445873435?__xts__[0]=68.ARD0Bo6pKci40x783wFG6wD9-CF9xTeLFrYtaM58gzDWHScGS4XhZ1NPrs4Y6cOxU2v_2GI1sD9Zk_znrZEa1JIKcb7IedRp1Yr9xc08OIrfu68dYMMaKe7Su9B_BO7uqme191LDsJ9xpBB9mIh0SPFgN5M-Bk_blfNgbIw8bCswaLH3NhdQYg&__tn__=C-R)

UFPR - Curitiba
Reported by the students and shared by Midia Ninja.

**Comment by anapaulagomes** [comment]
@giovanisleite there is a restriction on code about posts from Twitter and Facebook. Maybe is good adding this to the description of this issue and also adding a source that isn't either Facebook or Twitter.

**Comment by cuducos** [comment]
Many thanks for the topic/issue, @giovanisleite. Nowadays @turicas is already overflowed by [non-structure way to collect cases](https://twitter.com/turicas/status/1049346826355335169). Today we are going to deploy a Google Forms (1) that allows more people to share that curatorial task and (2) that allows us to receive already structured information.

By now I'm closing this issue to (a) avoid more overflow of information (b) and avoid causing the impression that we'll have stamina to take ideas put here into account. I ask for a little bit of patience until we deploy the Google From in a few hours : )
